---
- name: Create nginx data volume
  become: true
  file:
    path: "/docker/nginx"
    state: directory
    mode: "0755"
    owner: root

- name: Create nginx includes volume
  become: true
  file:
    path: "/docker/nginx/includes"
    state: directory
    mode: "0755"
    owner: root

- name: Ensure that proxy.conf is loaded into includes
  become: true
  copy:
    src: proxy.conf
    dest: /docker/nginx/includes
    owner: root
    group: root

- name: Ensure that ssl.conf is loaded into includes
  become: true
  copy:
    src: ssl.conf
    dest: /docker/nginx/includes
    owner: root
    group: root

- name: Ensure that default.conf is loaded
  become: true
  template:
    src: default.conf
    dest: /docker/nginx
    owner: root
    group: root
