- name: Ensure /etc/sudoers.d exists
  file:
    path: "/etc/sudoers.d"
    state: directory
    owner: root
    group: root

- name: Set the {{ time_zone }} timezone
  file:
    src: "/usr/share/zoneinfo/{{ time_zone }}"
    dest: "/etc/localtime"
    state: link
    owner: root
    group: root

- import_tasks: shell-config.yml

- import_tasks: setup-udev-rules.yml