---
- name: Ensure the user '{{ user_name }}' has zsh shell by default.
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    state: present
  become: yes

- name: Ensure that the .zprofile is loaded
  copy:
    src: .zprofile
    dest: /home/william/.zprofile
    owner: root
    group: root

- name: Create '.config' folder
  file:
    path: /home/william/.config
    state: directory
