---
- name: Ensure the user '{{ user_name }}' has zsh shell by default.
  become: true
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    state: present

- name: Ensure that the .zprofile is loaded
  become: true
  template:
    src: .zprofile
    dest: /home/william/.zprofile
    owner: root
    group: root

- name: Create '.config' folder
  become: true
  file:
    path: /home/william/.config
    state: directory

- name: Ensure that the aliasrc file is loaded
  become: true
  copy:
    src: aliasrc
    dest: /home/william/.config/aliasrc
    owner: root
    group: root

- name: Ensure that .zshrc file is loaded
  become: true
  copy:
    src: .zshrc
    dest: /home/william/.zshrc
    owner: root
    group: root
