---
- name: Update sshd configuration safely, avoid locking yourself out
  become: true
  become_user: root
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes