global:
  #By default, scrape targets every 30 seconds
  scrape_interval: 30s

  #Attach these labels to any time series or alerts when communicating with
  #external systems (federation, remote storage, Alertmanager)
  #external_labels:
  # monitor: 'ex-monitor'

scrape_configs:
  #The job name is added as a label `job=<job_name>`
  - job_name: "prometheus"
    # Override the interval that metrics are scraped
    scrape_interval: 15s
    static_configs:
      #targets: value can be a hostname or ip address
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["prometheus_node_exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:31192"]
