version: '3.3'

services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:latest
        restart: unless-stopped
        container_name: transmission-openvpn
        cap_add:
          - NET_ADMIN
        environment:
          - OPENVPN_PROVIDER: ${VPN_PROVIDER}
          - OPENVPN_CONFIG: ${VPN_COUNTRY}
          - OPENVPN_USERNAME: ${VPN_USERNAME}
          - OPENVPN_PASSWORD: ${VPN_PASSWORD}
          - LOCAL_NETWORK: 192.168.0.0/16
        logging:
          driver: json-file
          options:
            max-size: 10m
        ports:
          - '9091:9091'
        volumes:
          - '/docker/transmission:/data'
        labels:
          - "com.centurylinklabs.watchtower.enable=true"