global:
  #By default, scrape targets every 30 seconds
  scrape_interval: 30s

  #Attach these labels to any time series or alerts when communicating with
  #external systems (federation, remote storage, Alertmanager)
  #external_labels:
  # monitor: 'ex-monitor'

scrape_configs:
  #The job name is added as a label `job=<job_name>`
  - job_name: "prometheus"
    # Override the interval that metrics are scraped
    scrape_interval: 15s
    static_configs:
      #targets: value can be a hostname or ip address
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["prometheus_node_exporter:9100"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:31192"]
  - job_name: "home_assistant"
    scrape_interval: 20s
    metrics_path: /api/prometheus
    scheme: https
    bearer_token: "{{ ha_prometheus_token }}"
    static_configs:
      - targets: ["home.keystoneridge.duckdns.org"]
  - job_name: "snmp_synology"
    static_configs:
      - targets: ["{{ nas_ip }}"]
    metrics_path: "/snmp"
    params:
      auth: [synology]
      module: [if_mib, synology]
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: {{ ansible_host }}:9116 # The SNMP exporter's real hostname:port.
  - job_name: rack_ups
    metrics_path: /ups_metrics
    scrape_interval: 60s
    static_configs:
      - targets: ["{{ ansible_host }}:9199"]