---
- name: "Upgrade the system"
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install 'sudo'"
  apt:
    name: sudo
    state: present

- name: "Install zsh and shell completions"
  apt:
    name: ["zsh", "bash-completion"]
    state: present