---
- name: "Upgrade the system"
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install 'sudo'"
  become: true
  apt:
    name: sudo
    state: latest

- name: "Install zsh and shell completions"
  become: true
  apt:
    name: ["zsh", "bash-completion"]
    state: latest

- name: "Install htop"
  become: true
  apt:
    name: htop
    state: latest