---
- name: Ensure /etc/sudoers.d exists
  become: true
  file:
    path: "/etc/sudoers.d"
    state: directory
    owner: root
    group: root

- name: "Configure sudoers"
  become: true
  copy:
    src: "sudoers"
    dest: "/etc/sudoers.d/sudoers"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -csf %s"

- name: "Install 'sudo'"
  become: true
  apt:
    name: sudo
    state: latest
