---
- name: "Install 'sudo'"
  become: true
  become_user: root
  become_method: su
  apt:
    name: sudo
    state: latest

- name: Setup user
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    comment: "{{ user_full_name }}"
    groups: [ "sudo" ]
    state: present

- name: Ensure /etc/sudoers.d exists
  file:
    path: "/etc/sudoers.d"
    state: directory
    owner: root
    group: root

- name: "Configure sudoers"
  copy:
    src: "sudoers"
    dest: "/etc/sudoers.d/sudoers"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -csf %s"
