---
- name: Ensure /etc/sudoers.d exists
  become: true
  become_user: root
  become_method: su
  file:
    path: "/etc/sudoers.d"
    state: directory
    owner: root
    group: root

- name: Add user to 'sudo' group
  become: true
  become_user: root
  become_method: su
  command: "usermod -a -G sudo {{ user_name }}"

- name: "Configure sudoers"
  become: true
  become_user: root
  become_method: su
  copy:
    src: "sudoers"
    dest: "/etc/sudoers.d/sudoers"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -csf %s"

- name: "Install 'sudo'"
  become: true
  become_user: root
  become_method: su
  apt:
    name: sudo
    state: latest
