---
# Run by convention (so we'll pull in the additional yaml files here)

## First we'll do the system configuration first

## Set timezone - Format is in tz format
## https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#:~:text=Property%20Value%20%20Country%20code%20%20%20,Africa%2FAlgiers%20%20%20%20%20%20%2B01%3A00%20

- name: Set the {{ time_zone }} timezone
  become: true
  file:
    src: "/usr/share/zoneinfo/{{ time_zone }}"
    dest: "/etc/localtime"
    state: link
    owner: root
    group: root

## This configures everything for .zsh and your profile
## This requires {{ user_name }} to be your linux login username
## Requirements:
## - templates/.zprofile
## - files/aliasrc
- import_tasks: shell-config.yml

## This requires {{ user_name }} to be your linux login username
## Requirements: 
## - templates/sshd_config
- import_tasks: ssh-config.yml

## This replaces the 99-com.rules default file with the file included in this playbook
## Requirements:
## - files/99-com.rules
- import_tasks: setup-udev-rules.yml

# Install apps & software with apt
# Requirements:
# - files/sudoers
- import_tasks: apt.yml

# Configure samba with template
# Requirements:
# - templates/smb.conf
- import_tasks: configure-samba.yml