---
- name: Ensure '/mnt/nas/photos' is created
  become: true
  file:
    path: "/mnt/nas/photos"
    state: directory
    mode: "0777"
    owner: root
    group: root

# Test mount
#  sudo mount -t nfs 10.10.0.10:/volume1/Media/Movies /mnt/nas/movies
# Test unmount
#  sudo umount 10.10.0.10:/backups
- name: Mount 'Photos'
  become: true
  become_user: william
  become_method: sudo
  mount:
    src: "{{ nas_ip }}:/volume1/Photos"
    path: /mnt/nas/photos
    state: mounted
    mode: "0777"
    fstype: nfs