---
- name: Change subdomain to 'photos.*''
  become: true
  replace:
    path: "{{ docker_host_location }}/nginx/proxy-confs/piwigo.subdomain.conf.sample"
    regexp: "piwigo.*"
    replace: photos.*

- name: Load 'dockuwiki.conf'
  become: true
  copy:
    src: "{{ docker_host_location }}/nginx/proxy-confs/piwigo.subdomain.conf.sample"
    dest: "{{ docker_host_location }}/nginx/proxy-confs/piwigo.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william
