---
- import_tasks: import-config.yml

- name: Run 'HomeAssistant' - Docker Container
  docker_container:
    name: home-assistant
    image: homeassistant/home-assistant
    restart_policy: unless-stopped
    networks:
      - name: port-freedom
        ipv4_address: "{{ ha_container_ip }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker/home-assistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
#    devices:
#      - /dev/ttyACM0:/dev/ttyACM0:rwm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://{{ ha_container_ip }}:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    labels:
      com.centurylinklabs.watchtower.enable: "true"

# Blog about restarting on failure?? https://chrisschuld.com/2019/09/running-home-assistant-with-docker/