---
- name: Change subdomain to 'home.*''
  become: true
  replace:
    path: "{{ docker_host_location }}/nginx/proxy-confs/homeassistant.subdomain.conf.sample"
    regexp: "homeassistant.*"
    replace: home.*

- name: Load 'home-assistant.conf'
  become: true
  copy:
    src: "{{ docker_host_location }}/nginx/proxy-confs/homeassistant.subdomain.conf.sample"
    dest: "{{ docker_host_location }}/nginx/proxy-confs/ha.subdomain.conf"
    remote_src: true
    mode: "0777"
    owner: william
    group: william