- name: Create docker volume (prometheus)
  become: true
  file:
    path: "{{ host_docker_folder_location }}"
    state: directory
    mode: "0777"
    owner: root

- name: Create docker volume (prometheus data)
  become: true
  file:
    path: "{{ host_docker_folder_location }}/data"
    state: directory
    mode: "0777"
    owner: root

- name: Ensure that the prometheus configuration is loaded
  become: true
  copy:
    src: prometheus.yml
    dest: "{{ host_docker_folder_location }}/prometheus.yml"
    owner: root
    mode: "0777"
    group: root

- name: Ensure that the snmp.yml is loaded
  become: true
  copy:
    src: snmp.yml
    dest: "{{ host_snmp_explorer_location }}/snmp.yml"
    owner: root
    mode: "0777"
    group: root