- name: Create docker volume (prometheus)
  become: true
  file:
    path: "{{ host_docker_folder_location }}"
    state: directory
    mode: "0777"
    owner: root

- name: Create docker volume (prometheus data)
  become: true
  file:
    path: "{{ host_docker_folder_location }}/data"
    state: directory
    mode: "0777"
    owner: root

- name: Load 'nas.conf'
  become: true
  template:
    src: nas.subdomain.conf
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs"

- name: Ensure that the prometheus configuration is loaded
  become: true
  template:
    src: prometheus.yml
    dest: "{{ host_docker_folder_location }}/prometheus.yml"
    mode: "0777"
    owner: root

- name: Create docker volume (snmp)
  become: true
  file:
    path: "{{ host_snmp_explorer_location }}"
    state: directory
    mode: "0777"
    owner: root

- name: Ensure that the snmp.yml is loaded
  become: true
  copy:
    src: snmp.yml
    dest: "{{ host_snmp_explorer_location }}/snmp.yml"
    owner: root
    mode: "0777"
    group: root
