# Installs prometheus on the monitoring machine
- name: Run 'nut exporter' - Docker Container
  docker_container:
    name: nut_ups_data_exporter
    image: ghcr.io/druggeri/nut_exporter
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    env:
      NUT_EXPORTER_SERVER: "{{ ansible_host }}"
      NUT_EXPORTER_SERVERPORT: 3493
      NUT_EXPORTER_USERNAME: "{{ ups_monitor_username }}"
      NUT_EXPORTER_PASSWORD: "{{ ups_monitor_password }}"
      TZ: "{{ time_zone }}"
    ports:
      - 9199:9199
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    container_default_behavior: compatibility
