- name: Create prometheus directories create directory if they don't exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
    recurse: yes
  loop:
    - "{{ host_prometheus_folder_location }}/data"
    - "{{ host_prometheus_folder_location }}/config"

- name: Ensure that the prometheus configuration is loaded
  become: true
  template:
    src: prometheus.yml
    dest: "{{ host_prometheus_folder_location }}/config/prometheus.yml"
    mode: "0777"
    owner: root
  register: config

# Installs prometheus on the monitoring machine
- name: Run 'prometheus' - Docker Container
  docker_container:
    name: prometheus
    image: docker.io/prom/prometheus
    restart_policy: unless-stopped
    pull: true
    privileged: true
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ prometheus_container_ip }}"
    volumes:
      - "{{ host_prometheus_folder_location }}/config:/etc/prometheus"
      - "{{ host_prometheus_folder_location }}/data:/prometheus/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/query || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.prometheus.entrypoints: "websecure,web"
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.routers.prometheus.rule: "Host(`prometheus.zinkzone.tech`)"
      traefik.http.routers.prometheus.service: "prometheus"
      traefik.http.services.prometheus.loadBalancer.server.port: "9090"
      traefik.http.routers.prometheus.tls.certresolver: "letsencrypt"

- name: Restart prometheus if config changed
  docker_container:
    name: prometheus
    state: started
    restart: true
  when: config.changed

#This container will collect metrics for the host system
- name: Run 'node explorer' - Docker Container
  docker_container:
    name: prometheus_node_exporter
    image: quay.io/prometheus/node-exporter
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ nuc8_node_explorer_ip }}"
    command:
      - "--path.rootfs=/host"
    pull: true
    privileged: true
    restart_policy: unless-stopped
    pid_mode: host
    volumes:
      - "/:/host:ro,rslave"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9100 || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.node_explorer_nuc8.entrypoints: "websecure,web"
      traefik.http.routers.node_explorer_nuc8.tls: "true"
      traefik.http.routers.node_explorer_nuc8.rule: "Host(`nuc8-node.zinkzone.tech`)"
      traefik.http.routers.node_explorer_nuc8.service: "node_explorer_nuc8"
      traefik.http.services.node_explorer_nuc8.loadBalancer.server.port: "9100"
      traefik.http.routers.node_explorer_nuc8.tls.certresolver: "letsencrypt"      

- name: Create docker volume (snmp)
  become: true
  file:
    path: "{{ host_snmp_explorer_location }}"
    state: directory
    mode: "0777"
    owner: root

- name: Ensure that the snmp.yml is loaded
  become: true
  template:
    src: snmp.yml
    dest: "{{ host_snmp_explorer_location }}/snmp.yml"
    owner: root
    mode: "0777"
    group: root

- name: Run 'snmp explorer' - Docker Container
  docker_container:
    name: nas_snmp_exporter
    image: prom/snmp-exporter
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ nas_snmp_explorer_ip }}"
    privileged: true
    pull: true
    restart_policy: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ host_snmp_explorer_location}}/snmp.yml:/etc/snmp_exporter/snmp.yml"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9116 || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.snmp_explorer.entrypoints: "websecure,web"
      traefik.http.routers.snmp_explorer.tls: "true"
      traefik.http.routers.snmp_explorer.rule: "Host(`nas-snmp.zinkzone.tech`)"
      traefik.http.routers.snmp_explorer.service: "snmp_explorer"
      traefik.http.services.snmp_explorer.loadBalancer.server.port: "9116"
      traefik.http.routers.snmp_explorer.tls.certresolver: "letsencrypt"

# # The container below collects docker/container metrics
# # NOTE: This is not compatible with arm architecture such as RaspberryPi or ARM Macs
# # Uncomment below to enable cadvisor on an AMD64 Architecture
- name: Run 'cadvisor' - Docker Container
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ cadvisor_ip }}"
    privileged: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/docker/portainer:/data"
    devices:
      - /dev/kmsg
    # Healthcheck built into container
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.cadvisor.entrypoints: "websecure,web"
      traefik.http.routers.cadvisor.tls: "true"
      traefik.http.routers.cadvisor.rule: "Host(`cadvisor.zinkzone.tech`)"
      traefik.http.routers.cadvisor.service: "cadvisor"
      traefik.http.services.cadvisor.loadBalancer.server.port: "8080"
      traefik.http.routers.cadvisor.tls.certresolver: "letsencrypt"     