---
- name: Clone Automatic Southwest check-in (scripts)
  git:
    repo: "{{ southwest_ssh_git }}"
    dest: /home/william/git/Southwest.AutomaticCheckIn
    accept_hostkey: yes

- name: Create 'Southwest Check-in' folder
  become: true
  file:
    path: /home/william/Southwest-Check-In
    mode: ugo=rwx
    owner: william
    group: william
    state: directory

- name: Move '.sh' files to Southwest directory
  become: true
  copy:
    remote_src: true
    src: /home/william/git/Southwest.AutomaticCheckIn/scripts/
    dest: /home/william/Southwest-Check-In/
    mode: ugo=rwx
    owner: william
    group: william

- name: Move template file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/template.env
    dest: /home/william/Southwest-Check-In/template.env
    remote_src: yes

- name: Move docker-compose file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/docker-compose.yaml
    dest: /home/william/Southwest-Check-In/docker-compose.yml
    remote_src: yes

- name: Remove git files
  file:
    path: /home/william/git
    state: absent
