---
- name: Check if Automatic Southwest Check-in scripts exists
  stat:
    path: /home/william/Southwest.AutomaticCheckIn/scripts
  register: swac_scripts

- name: Clone Automatic Southwest check-in (scripts)
  git:
    repo: git@github.com:ZinkNotTheMetal/Southwest.AutomaticCheckIn.git
    dest: /home/william/git/Southwest.AutomaticCheckIn
    accept_hostkey: yes
  when: not swac_scripts.stat.exists

- name: Create 'Southwest Check-in' folder
  file:
    path: /home/william/Southwest-Check-In
    state: directory

#- name: Find shell files to move
#  find:
#    paths: /home/william/git/Southwest.AutomaticCheckIn/scripts/
#    file_type: file
#    patterns: "*.sh"
#    use_regex: no
#    recurse: no
#  register: script_files_to_move
#  when: not swac_scripts.stat.exists

#- name: Move all shell files
#  copy:
#    src: "{{ item }}"
#    dest: /home/william/Southwest-Check-In
#    remote_src: yes
#  with_items:
#    - "{{ script_files_to_move.files }}"
#  when: not swac_scripts.stat.exists

- name: Move shell files to Southwest directory
  copy:
    src: "{{ items }}"
    dest: /home/william/Southwest-Check-In
    remote_src: yes
  with_fileglob:
    - "/home/william/git/Southwest.AutomaticCheckIn/scripts /*.sh"
  when: not swac_scripts.stat.exists

- name: Move template file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/template.env
    dest: /home/william/Southwest-Check-In/template.env
    remote_src: yes
  when: not swac_scripts.stat.exists

- name: Move docker-compose file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/docker-compose.yaml
    dest: /home/william/Southwest-Check-In/docker-compose.yml
    remote_src: yes
  when: not swac_scripts.stat.exists

- name: Get all .sh files
  find:
    paths: /home/william/Southwest-Check-In
    patterns: "*.sh"
    file_type: file
  register: files_to_execute

- name: Make .sh files executable
  file:
    dest: "{{ item }}"
    mode: a+x
  with_items:
    - "{{ files_to_execute.files }}"

- name: Remove git files
  file:
    path: /home/william/git/Southwest.AutomaticCheckIn
    state: absent
  when: not swac_scripts.stat.exists
