---
- name: Clone Automatic Southwest check-in (scripts)
  git:
    repo: "{{ southwest_ssh_git }}"
    dest: /home/william/git/Southwest.AutomaticCheckIn
    accept_hostkey: yes

- name: Create 'Southwest Check-in' folder
  file:
    path: /home/william/Southwest-Check-In
    state: directory

- name: Move shell files to Southwest directory
  copy:
    remote_src: true
    src: /home/william/git/Southwest.AutomaticCheckIn/scripts/
    dest: /home/william/Southwest-Check-In/
    mode: a+x

- name: Move template file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/template.env
    dest: /home/william/Southwest-Check-In/template.env
    remote_src: yes

- name: Move docker-compose file
  copy:
    src: /home/william/git/Southwest.AutomaticCheckIn/docker-compose.yaml
    dest: /home/william/Southwest-Check-In/docker-compose.yml
    remote_src: yes

- name: Remove git files
  file:
    path: /home/william/git
    state: absent
