---
- import_tasks: move-files.yml

- name: Run 'swag' - Docker Container
  docker_container:
    name: dns-cert-manager
    image: ghcr.io/linuxserver/swag
    restart_policy: unless-stopped
    networks:
      - name: bridge
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_host_location }}:/config"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ time_zone }}"
      URL: "{{ dns_to_renew }}"
      SUBDOMAINS: wildcard
      VALIDATION: "{{ dns_provider }}"
      DUCKDNSTOKEN: "{{ dns_token }}"
      EMAIL: "{{ contact_email }}"
    ports:
      - 40443:443
      - 8180:80
    labels:
      com.centurylinklabs.watchtower.enable: "true"
