- name: Load 'mealie.conf'
  become: true
  copy:
    src: "{{ docker_host_location }}/nginx/proxy-confs/mealie.subdomain.conf.sample"
    dest: "{{ docker_host_location }}/nginx/proxy-confs/mealie.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william