---
- name: Ensure /etc/ssh/keys is a valid directory
  become: true
  become_user: root
  become_method: sudo
  file:
    path: "/etc/ssh/keys"
    state: directory
    mode: "0600"
    owner: root

- name: Update sshd configuration safely, avoid locking yourself out
  become: true
  become_user: root
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
    backup: yes

- name: Ensure that the .zprofile is loaded
  become: true
  template:
    src: .zprofile
    dest: /home/william/.zprofile
    owner: root
    group: root
