---
- name: Ensure that the ups.conf is loaded
  become: true
  copy:
    src: eaton.conf
    dest: /etc/nut/ups.conf
    owner: root
    group: root

- name: Ensure that upsd.conf is loaded
  become: true
  copy:
    src: upsd.conf
    dest: /etc/nut/upsd.conf
    owner: root
    group: root

- name: Ensure that upsd.users is loaded
  become: true
  template:
    src: upsd.users
    dest: /etc/nut/upsd.users
    owner: root
    group: root

- name: Ensure that upsmon.conf is loaded
  become: true
  template:
    src: upsmon.conf
    dest: /etc/nut/upsd.conf
    owner: root
    group: root

- name: Ensure that custom shutdown script is loaded
  become: true
  template:
    src: home-shutdown.sh
    dest: /etc/nut/home-shutdown.sh
    owner: root
    group: root
    mode: ugo=rwx
