---
- name: Check If Docker Is Installed
  command: docker --version
  register: docker_valid
  ignore_errors: true

# Completely setup docker
- name: Remove old docker versions
  become: true
  apt:
    pkg:
      - containerd
      - runc
    state: absent
  when: docker_valid.failed

- name: Install pre-requisites
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
    state: latest
    update_cache: yes
  when: docker_valid.failed

- name: Add signing key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: docker_valid.failed

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: docker_valid.failed

- name: Install Docker & dependencies
  become: true
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true
  when: docker_valid.failed

- name: Docker is running
  service:
    name: docker
    state: started

- name: Find physical network adapter
  command: find /sys/class/net -type l -not -lname '*virtual*' -not -name 'wlp0s20f3' -printf '%f\n'
  register: physical_interfaces_cmd
  changed_when: false
  check_mode: false

- name: Create IPVLAN L3
  become: true
  docker_network:
    name: docker_ipvlan
    driver: ipvlan
    driver_options:
      parent: "{{ physical_interfaces_cmd.stdout_lines[0] }}"
      ipvlan_mode: l3
    ipam_config:
      - subnet: "{{ docker_network_ip_outside }}/24"
      - subnet: "{{ docker_network_ip_inside }}/24"

    # - name: Ensure no internet access for ipvlan_no_internet network
    #   command: ip route del default via 192.168.20.1
    #   ignore_errors: yes

    # - name: Allow communication between Docker networks
    #   ufw:
    #     rule: allow
    #     from_ip: 192.168.20.0/24
    #     to_ip: 192.168.10.0/24
    #     comment: Allow communication between ipvlan_no_internet and ipvlan_internet

    # - name: Block internet access for ipvlan_no_internet network
    #   ufw:
    #     rule: deny
    #     from_ip: 192.168.20.0/24
    #     to_ip: any
    #     comment: Block internet access for ipvlan_no_internet network
    #     direction: out

- name: Create custom bridge docker network
  become: true
  docker_network:
    name: curidge

- name: Create docker data volume
  become: true
  file:
    path: "/docker"
    state: directory
    mode: "0755"
    owner: root
    recurse: yes

- name: Add '{{ user_name }}' user to docker group
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
