---
# Description
# Create and start internal wiki page
- name: Ensure '/mnt/nas' is created
  become: true
  file:
    path: "/mnt/nas/wiki"
    state: directory
    mode: "0777"
    owner: root
    group: root

# Test mount
#  sudo mount -t nfs 10.10.0.10:/volume1/Media/Movies /mnt/nas/movies
# Test unmount
#  sudo umount 10.10.0.10:/backups
- name: Mount 'wiki'
  become: true
  become_user: william
  become_method: sudo
  mount:
    src: "{{ nas_ip }}:/volume1/Wiki"
    path: /mnt/nas/wiki
    state: mounted
    fstype: nfs

- name: Run 'DokuWiki' Docker Container
  docker_container:
    name: wiki
    image: linuxserver/dokuwiki:latest
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: port-freedom
        ipv4_address: "{{ dokuwiki_container_ip }}"
    volumes:
      - "/mnt/nas/wiki:/config/dokuwiki/data:rw"
    env:
      TZ: "{{ time_zone }}"
      PUID: 1000
      PGID: 1000
    labels:
      com.centurylinklabs.watchtower.enable: "true"
