---
# Description: Run all home-server applications
- import_tasks: docker-setup.yml

- import_tasks: setup-watchtower.yml

- import_tasks: setup-portainer.yml

- import_tasks: setup-swag.yml

- import_tasks: setup-transmission.yml

- import_tasks: setup-plex.yml

- import_tasks: setup-tautulli.yml

- import_tasks: setup-overseerr.yml

- import_tasks: setup-traccar.yml

# Consider replacement with HOMARR
- import_tasks: setup-uptime-kuma.yml