---
# Loads the proper subdomain from nginx
- name: Load 'portainer.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Run 'Portainer' - Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    restart_policy: unless-stopped
    pull: true
    container_default_behavior: compatiblity
    network_mode: curidge
    networks:
      - name: curidge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/docker/portainer:/data"
    ports:
      - 9000:9000
    labels:
      com.centurylinklabs.watchtower.enable: "true"