# pgAdmin
# Documentation: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
# Purpose: Database web client for connecting to Postgres databases
- name: Create docker volume for pgadmin directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ host_pgadmin_folder_location }}"

- name: Run 'pgadmin' - Docker Container
  docker_container:
    name: pgadmin
    image: dpage/pgadmin4:latest
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_default_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_default_password }}"
    volumes:
      - "{{ host_pgadmin_folder_location }}:/var/lib/pgadmin"
      - "{{ host_pgadmin_folder_location }}/config.py:/pgadmin4/config.py"
    ports:
      - 5050:80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
