# Tautulli
# Documentation: https://github.com/Tautulli/Tautulli
# Purpose: Keep statistics on what I watch and how often I watch Plex items

- name: Create 'tautulli' data volume
  become: true
  file:
    path: "{{ host_tautulli_folder_location }}"
    state: directory
    mode: "0755"
    owner: root

- name: Run 'tautulli' - Docker Container
  docker_container:
    name: tautulli
    image: tautulli/tautulli
    restart_policy: unless-stopped
    networks:
      - name: port-freedom
        ipv4_address: "{{ tautulli_container_ip }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ host_tautulli_folder_location }}:/config"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ time_zone }}"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
