# Sonarr
# Documentation: https://github.com/linuxserver/docker-sonarr
# Purpose: To help automate movement of tv show media
- name: Create docker volume
  become: true
  file:
    path: "{{ host_sonarr_folder_location }}/config"
    state: directory
    mode: "0755"
    owner: root

- name: Run 'Sonarr' - Docker Container
  docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ host_radarr_folder_location }}/config:/config"
      - "{{ host_transmission_folder_location }}:/data"
      - "/mnt/nas/tv:/tv"
    ports:
      - 8989:8989
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    container_default_behavior: compatibility
