# Uptime-Kuma
# Documentation: https://github.com/louislam/uptime-kuma
# Purpose: To keep track of what is up & running locally vs via internet
- name: Ensure '/docker/uptime-kuma' is created
  become: true
  file:
    path: "{{ host_kuma_folder_location }}"
    state: directory
    mode: "0777"
    owner: root
    group: root

- name: Run 'Uptime-Kuma' - Docker Container
  docker_container:
    name: uptime
    image: louislam/uptime-kuma
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ host_kuma_folder_location }}:/app/data"
    ports:
      - 3001:3001
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    container_default_behavior: compatibility