# Traccar
# Documentation: https://www.traccar.org/documentation/
# Purpose: Host Life360 like application locally for Home Assistant
# https://github.com/traccar/traccar-docker?tab=readme-ov-file
- name: Create Traccar Directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ host_traccar_folder_location }}/config"
    - "{{ host_traccar_folder_location }}/logs"
    - "{{ host_traccar_folder_location }}/db-data"
    - "{{ host_traccar_folder_location }}/db-backups"

- name: Run 'Traccar DB' - Docker Container
  docker_container:
    name: traccar-db
    image: postgres:17-alpine
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ traccar_db_container_ip }}"
    volumes:
      - "{{ host_traccar_folder_location }}/db-backups:/backups:rw"
      - "{{ host_traccar_folder_location }}/db-data:/data/postgres"
    env:
      POSTGRES_USER: "{{ traccar_db_user }}"
      POSTGRES_PASSWORD: "{{ traccar_db_password }}"
      POSTGRES_DB: "{{ traccar_db_name }}"
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 8s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"

- name: Ensure the 'traccar' config is loaded
  become: true
  template:
    src: traccar.conf
    dest: "{{ host_traccar_folder_location }}/config/traccar.xml"
    owner: root
    group: root

- name: Traccar Docker Container
  docker_container:
    name: traccar
    image: traccar/traccar:6-alpine
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ traccar_container_ip }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ host_traccar_folder_location }}/config/traccar.xml:/opt/traccar/conf/traccar.xml:ro"
      - "{{ host_traccar_folder_location }}/logs:/opt/traccar/logs:rw"
    links:
      - traccar-db:traccar-db
    env:
      TZ: "{{ time_zone }}"
      VERSION: "docker"
    healthcheck:
     test: "wget --no-verbose --tries=1 --spider http://localhost:8082 || exit 1"
     start_interval: 15s
     interval: 20s
     timeout: 8s
     retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
