# Plex
# Documentation: https://www.plex.tv
# Purpose: Host Plex media center on my network to watch TV / Movies I have ripped from DVD's
- name: Ensure '/mnt/nas' is created
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: root
    group: root
  with_items:
    - "/mnt/nas/movies"
    - "/mnt/nas/tv"
    - "{{ host_plex_folder_location }}"

# Test mount
#  sudo mount -t nfs 10.10.0.10:/volume1/Media/Movies /mnt/nas/movies
#  sudo mount -t nfs 10.10.0.10:/volume1/Media/TV\ Shows /mnt/nas/tv
#  sudo mount -t nfs 10.10.0.10:/volume1/Files/Books /mnt/nas/books
# Test unmount
#  sudo umount 10.10.0.10:/backups
- name: Mount 'Movies'
  become: true
  mount:
    src: "{{ nas_ip }}:/volume1/Media/Movies"
    path: /mnt/nas/movies
    state: mounted
    fstype: nfs

- name: Mount 'TV Shows'
  become: true
  mount:
    src: "{{ nas_ip }}:/volume1/Media/TV\ Shows"
    path: /mnt/nas/tv
    state: mounted
    fstype: nfs

- name: Run 'plex' - Docker Container
  docker_container:
    name: plex
    image: lscr.io/linuxserver/plex
    restart_policy: unless-stopped
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ plex_container_ip }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ host_plex_folder_location }}/config:/config"
      - "{{ host_plex_folder_location }}/transcode:/transcode"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/nas/movies:/Movies"
      - "/mnt/nas/tv:/TV"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
      PLEX_CLAIM: "{{ plex_claim_token }}"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
