# Portainer
# Documentation: https://docs.portainer.io
# Purpose: To provide an easy to navigate UI for managing docker containers
- name: Create nginx data volume
  become: true
  file:
    path: "{{ host_portainer_folder_location }}"
    state: directory
    mode: "0755"
    owner: root

- name: Run 'Portainer' - Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:alpine
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ host_portainer_folder_location }}:/data"
    ports:
      - 9000:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9000/api/system/status || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
