# Radarr
# Documentation: https://docs.linuxserver.io/images/docker-radarr
# Purpose: To help automate movement of media
- name: Create docker volume
  become: true
  file:
    path: "{{ host_prowlarr_folder_location }}/config"
    state: directory
    mode: "0755"
    owner: root

- name: Run 'Prowlarr' - Docker Container
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
      TZ: "{{ time_zone }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ host_prowlarr_folder_location }}/config:/config"
    ports:
      - 9696:9696
    healthcheck:
      test: ["CMD", "curl", "-kL", "http://localhost:9696"]
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
