##################################################################################################
## Load DNS configs below here
##################################################################################################
- name: Load 'portainer.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Load 'nas.conf'
  become: true
  template:
    src: nas.subdomain.conf
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs"

- name: Load 'tautulli.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/tautulli.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/tautulli.subdomain.conf"
    remote_src: true
    mode: "0774"
    owner: william
    group: william

- name: Change server for tautulli
  become: true
  replace:
    path: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/tautulli.subdomain.conf"
    regexp: "set \\$upstream_app.*$"
    replace: "set $upstream_app {{ tautulli_container_ip }};"

- name: Load 'overseerr.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/overseerr.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/overseerr.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Change overseerr server for nginx
  become: true
  replace:
    path: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/overseerr.subdomain.conf"
    regexp: "set \\$upstream_app.*$"
    replace: "set $upstream_app {{ overseerr_container_ip }};"

- name: Load 'node-red.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/node-red.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/node-red.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Change server for node-red
  become: true
  replace:
    path: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/node-red.subdomain.conf"
    regexp: "set \\$upstream_app.*$"
    replace: "set $upstream_app {{ nr_container_ip }};"

- name: Load 'homarr.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/homarr.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/homarr.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Load 'grafana.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/grafana.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/grafana.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Load 'esphome.conf'
  become: true
  copy:
    src: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/esphome.subdomain.conf.sample"
    dest: "{{ host_cert_manager_folder_location }}/nginx/proxy-confs/esphome.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Restart SWAG after DNS entries changed for DNS entries
  docker_container:
    name: swag
    state: started
    restart: true
##################################################################################################
