---
# Description: Setup nginx and swag for internal networking
- name: Create nginx data volume
  become: true
  file:
    path: "{{ cert_manager_folder_location }}"
    state: directory
    mode: "0755"
    owner: root

- name: Run 'swag' - Docker Container
  docker_container:
    name: dns-cert-manager
    image: ghcr.io/linuxserver/swag
    restart_policy: unless-stopped
    networks:
      - name: curidge
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ cert_manager_folder_location }}:/config"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ time_zone }}"
      URL: "{{ dns_to_renew }}"
      SUBDOMAINS: wildcard
      VALIDATION: "{{ dns_provider }}"
      DUCKDNSTOKEN: "{{ dns_token }}"
      EMAIL: "{{ contact_email }}"
    capabilities:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
    labels:
      com.centurylinklabs.watchtower.enable: "true"

##################################################################################################
## Load DNS configs below here
##################################################################################################
- name: Load 'portainer.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/portainer.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Change subdomain to 'up.*'' for uptime-kuma
  become: true
  replace:
    path: "{{ cert_manager_folder_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf.sample"
    regexp: "uptime-kuma.*"
    replace: up.*

- name: Load 'uptime-kuma.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Load 'mealie.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/mealie.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/mealie.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Change subdomain to 'photos.*'' for piwigo
  become: true
  replace:
    path: "{{ cert_manager_folder_location }}/nginx/proxy-confs/piwigo.subdomain.conf.sample"
    regexp: "piwigo.*"
    replace: photos.*

- name: Load 'piwigo.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/piwigo.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/piwigo.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Change subdomain to 'wiki.*''
  become: true
  replace:
    path: "{{ cert_manager_folder_location }}/nginx/proxy-confs/dokuwiki.subdomain.conf.sample"
    regexp: "dokuwiki.*"
    replace: wiki.*

- name: Load 'dockuwiki.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/dokuwiki.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/dokuwiki.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william

- name: Load 'nas.conf'
  become: true
  template:
    src: nas.subdomain.conf
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs"

- name: Load 'tautulli.conf'
  become: true
  copy:
    src: "{{ cert_manager_folder_location }}/nginx/proxy-confs/tautulli.subdomain.conf.sample"
    dest: "{{ cert_manager_folder_location }}/nginx/proxy-confs/tautulli.subdomain.conf"
    remote_src: true
    mode: "0755"
    owner: william
    group: william
##################################################################################################
