---
# Description: Setup nginx and swag for internal networking
- name: Create nginx data volume
  become: true
  file:
    path: "{{ docker_host_location }}"
    state: directory
    mode: "0755"
    owner: root

- name: Load 'nas.conf'
  become: true
  template:
    src: nas.subdomain.conf
    dest: "{{ docker_host_location }}/nginx/proxy-confs"

- name: Run 'swag' - Docker Container
  docker_container:
    name: dns-cert-manager
    image: ghcr.io/linuxserver/swag
    restart_policy: unless-stopped
    networks:
      - name: curidge
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_host_location }}:/config"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ time_zone }}"
      URL: "{{ dns_to_renew }}"
      SUBDOMAINS: wildcard
      VALIDATION: "{{ dns_provider }}"
      DUCKDNSTOKEN: "{{ dns_token }}"
      EMAIL: "{{ contact_email }}"
    capabilities:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
    labels:
      com.centurylinklabs.watchtower.enable: "true"
