---
# Description:
# Uptime kuma running on app-server
- name: Ensure '/docker/uptime-kuma' is created
  become: true
  file:
    path: "/docker/uptime-kuma"
    state: directory
    mode: "0777"
    owner: root
    group: root

- name: Run 'Uptime-Kuma' - Docker Container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: curidge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/docker/uptime-kuma:/app/data"
    ports:
      - 3001:3001
    labels:
      com.centurylinklabs.watchtower.enable: "true"

- name: Change subdomain to 'up.*''
  become: true
  replace:
    path: "{{ docker_host_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf.sample"
    regexp: "uptime-kuma.*"
    replace: up.*

- name: Load 'home-assistant.conf'
  become: true
  copy:
    src: "{{ docker_host_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf.sample"
    dest: "{{ docker_host_location }}/nginx/proxy-confs/uptime-kuma.subdomain.conf"
    remote_src: true
    mode: "0777"
    owner: william
    group: william