---
- import_tasks: install.yml

- name: Create docker data volume
  path: "/docker"
  state: directory
    mode: '0755'
    owner: root

- name: Add ansible user to docker group
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes

- import_tasks: create-network.yml