---
- import_tasks: mount-media.yml

- name: Run 'plex' - Docker Container
  docker_container:
    name: plex
    image: lscr.io/linuxserver/plex
    restart_policy: unless-stopped
    networks:
      - name: port-freedom
        ipv4_address: "{{ plex_container_ip }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/nas/plex:/config"
      - "/docker/plex/transcode:/transcode"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/nas/movies:/Movies"
      - "/mnt/nas/tv:/TV Shows"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    labels:
      com.centurylinklabs.watchtower.enable: "true"