---
- name: Install 'nfs' - file sharing
  become: true
  apt:
    name: nfs-common
    state: latest

- name: Ensure '/mnt/nas' is created
  become: true
  file:
    path: /mnt/nas
    state: directory
    owner: root
    group: root

- name: Mount 'Movies'
  become: true
  mount:
    src: "{{ nas_ip }}:/volume1/Media/Movies"
    path: /mnt/nas/movies
    state: mounted
    opts: remount,rw
    fstype: nfs

- name: Mount 'TV Shows'
  become: true
  mount:
    src: "{{ nas_ip }}:volume1/Media/TV\ Shows"
    path: /mnt/nas/tv
    state: mounted
    opts: remount,rw
    fstype: nfs