---
- name: Ensure '/mnt/nas' is created
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: root
    group: root
  with_items:
    - "/mnt/nas/movies"
    - "/mnt/nas/tv"

# Test mount
#  sudo mount -t nfs 10.10.0.10:/volume1/Media/Movies /mnt/nas/movies
# Test unmount
#  sudo umount 10.10.0.10:/backups
- name: Mount 'Movies'
  become: true
  become_user: william
  become_method: sudo
  mount:
    src: "{{ nas_ip }}:/volume1/Media/Movies"
    path: /mnt/nas/movies
    state: mounted
    fstype: nfs

- name: Mount 'TV Shows'
  become: true
  become_user: william
  become_method: sudo
  mount:
    src: "{{ nas_ip }}:/volume1/Media/TV\ Shows"
    path: /mnt/nas/tv
    state: mounted
    fstype: nfs